var datos=[];

datos['data_general']=['casual', 'elefante', 'fusilamiento', 'acreedor', 'jefatura', 'cuba', 'felicidad', 'ilegalizar', 'monarquía', 'barcelona',
						'osezno', 'estilismo', 'cineasta', 'voluminoso', 'suavidad', 'clínica', 'exportar', 'doloroso', 'hipnotizador', 'cabaña',
						'flauta', 'susurro', 'cariz', 'hospital', 'acné', 'exterior', 'vulcanólogo', 'depravado', 'noctámbulo', 'portada',
						'folio', 'hígado', 'gas', 'sonambulismo', 'rodaballo', 'hepatitis', 'embudo', 'claustrofobia', 'barato', 'clima',
						'cámara', 'paje', 'eliminar', 'hispano', 'culebrón', 'déspota', 'lavandería', 'estaca', 'estupidez', 'chimpancé',
						'gacetilla', 'templo', 'cincel', 'paranoico', 'pomo', 'retórico', 'vibrar', 'despliegue', 'ceniza', 'demográfico',
						'lícito', 'concreto', 'atípico', 'creación', 'destilar', 'rasgo', 'glotón', 'monótono', 'vulgar', 'envejecimiento',
						'corrida', 'semifinalista', 'cromo', 'fiabilidad', 'despacito', 'columna', 'conforme', 'travesaño', 'excedente', 'neuralgia',
						'zoofilia', 'agrietar', 'comprimir', 'colchón', 'cegador', 'envío', 'contraer', 'elástico', 'deshollinador', 'modalidad',
						'emplear', 'marroquinería', 'sortear', 'racimo', 'delegado', 'inca', 'imperial', 'marginación', 'escándalo', 'gorrión',
						'hada', 'denario', 'desconectar', 'celebrar', 'demonio', 'grúa', 'súplica', 'influyente', 'trenzar', 'efusivo',
						'euro', 'cobardía', 'proyector', 'iluminar', 'dudoso', 'elitista', 'tranvía', 'símil', 'cometa', 'diluir',
						'profesionalidad', 'monada', 'cetáceo', 'celuloide', 'cola', 'comer', 'balada', 'enfoque', 'hippy', 'buhardilla',
						'emirato', 'futurólogo', 'purificar', 'textual', 'grillo', 'satélite', 'fotocopiar', 'contextual', 'charol', 'membrana',
						'engañosa', 'maletero', 'silbar', 'sismólogo', 'ciclón', 'cigüeñal', 'cueva', 'burocrático', 'cutáneo', 'encefalografía',
						'compensar', 'mariscal', 'velocidad', 'ejército', 'corrupto', 'catalejo', 'enloquecer', 'churrero', 'abejón', 'aerosol',
						'señoril', 'fichaje', 'pufo', 'cizaña', 'corral', 'humedecer', 'voltear', 'enfundar', 'monopolizar', 'cobre',
						'derrapar', 'laguna', 'sonrisa', 'barrica', 'correa', 'truco', 'coloquio', 'cuello', 'consciente', 'evangélico',
						'esoterismo', 'contador', 'adherir', 'afilar', 'empeñado', 'frágil', 'exhausto', 'desagüe', 'oftalmólogo', 'balonmano',
						'híbrido', 'abad', 'hipermercado', 'cuerpo', 'acomplejar', 'decibelio', 'endeble', 'ministro', 'economista', 'gobernar',
						'caña', 'recreativo', 'existir', 'gasa', 'explorador', 'salud', 'noticia', 'seísmo', 'tilde', 'solvente',
						'impedir', 'solfeo', 'trinidad', 'horrible', 'contraportada', 'inyección', 'discografía', 'cebú', 'esplendor', 'estiércol',
						'acelerómetro', 'alunizaje', 'cárnico', 'pesada', 'guiñar', 'madeja', 'cefalea', 'chispa', 'dueña', 'vitrina',
						'fábula', 'desafiar', 'capucha', 'justicia', 'mora', 'apagón', 'gorgojo', 'objetividad', 'peñasco', 'pincel',
						'centollo', 'rehabilitar', 'formulario', 'reclinar', 'zigzaguear', 'abrasivo', 'partida', 'quitamiedos', 'abalorio', 'global',
						'geógrafo', 'estival', 'loba', 'barajar', 'bandera', 'desplomar', 'renovación', 'acidez', 'hermano', 'condena',
						'dictar', 'habitar', 'complacer', 'juego', 'cerrar', 'nudo', 'erección', 'manojo', 'jirafa', 'preocupación',
						'cartero', 'ñoñería', 'conocer', 'cruel', 'encaje', 'circense', 'clonación', 'cuidado', 'bambú', 'búho',
						'cordura', 'destruir', 'cardíaco', 'depósito', 'fitófago', 'pensión', 'diabólico', 'director', 'principio', 'chillido',
						'dictatorial', 'exaltamiento', 'visionario', 'tricéfalo', 'acróbata', 'centeno', 'cláusula', 'diosa', 'abadía', 'pulsador'];

datos['data_general2']=['pesadilla', 'escaparate', 'cebolla', 'desánimo', 'chupete', 'exudar', 'ultravioleta', 'enchufe', 'centrifugado', 'glamour',
						'yugo', 'prólogo', 'cleptómano', 'fábrica', 'relación', 'conectar', 'menstruación', 'bicéfalo', 'fotógrafo', 'cruz',
						'mísero', 'esfumar', 'candil', 'esposa', 'hielo', 'noble', 'corroer', 'dibujante', 'delictivo', 'cumpleaños',
						'cisne', 'empuñadura', 'tocado', 'iceberg', 'lanzagranadas', 'ejemplar', 'impregnar', 'tanqueta', 'drama', 'medida',
						'increíble', 'catarro', 'prohibitivo', 'fármaco', 'celulitis', 'alcantarilla', 'señuelo', 'melena', 'licorera', 'mucosa',
						'trombón', 'hacha', 'sepultura', 'deglutir', 'aumentar', 'autor', 'caravana', 'convexo', 'despeñadero', 'peladillo',
						'telaraña', 'cualificado', 'república', 'útero', 'prestar', 'ciervo', 'tuétano', 'balbucear', 'dama', 'edificar',
						'reencarnación', 'indefinidamente', 'empírico', 'tirita', 'zambomba', 'chubasco', 'engordar', 'judía', 'silbato', 'dial',
						'bucólico', 'previsible', 'chasquido', 'firmar', 'simpático', 'fascículo', 'tebeo', 'diseñador', 'branquia', 'disfraz',
						'molinero', 'nochebuena', 'diábolo', 'solver', 'amistad', 'cacatúa', 'incitar', 'cristal', 'después', 'espectro',
						'medalla', 'desempaquetar', 'inviable', 'puré', 'galo', 'sindicalista', 'fácil', 'serpentina', 'dintel', 'espionaje',
						'edad', 'manutención', 'champú', 'gastado', 'enojar', 'muérdago', 'daltónico', 'clímax', 'contrario', 'babosa',
						'emocional', 'recubrimiento', 'subdirección', 'narcótico', 'cervical', 'traducción', 'flamante', 'rallado', 'honor', 'descargar',
						'planeta', 'tabú', 'escaño', 'higiene', 'sacacorchos', 'personaje', 'loco', 'consumar', 'estirpe', 'asíncrono',
						'cobaya', 'enjambre', 'extraño', 'falsificar', 'tabla', 'kilometraje', 'idioma', 'bachata', 'consciencia', 'alquitrán',
						'grupal', 'fantasma', 'coser', 'cultivo', 'fresón', 'cazuela', 'retrete', 'dogmatismo', 'grulla', 'divinamente',
						'cuadro', 'enemistad', 'traslado', 'torneo', 'circunvalación', 'provocador', 'empalme', 'culebra', 'delfín', 'esquí',
						'cálido', 'abreviado', 'rodaja', 'cáliz', 'píldora', 'núcleo', 'desdeñable', 'adoquín', 'desorden', 'disco',
						'rural', 'mascota', 'zócalo', 'laboratorio', 'descolgar', 'número', 'derramado', 'obsesivo', 'desistir', 'cuaresma',
						'mecánico', 'bodega', 'edema', 'saxofón', 'brutalidad', 'bombero', 'fosa', 'vampiresa', 'cerezo', 'chivata',
						'maniaco', 'espantoso', 'estático', 'cópula', 'ensamblado', 'geólogo', 'eólico', 'fallecimiento', 'gorro', 'concepto',
						'descansillo', 'desove', 'leñador', 'jabonera', 'disimular', 'mal', 'vítreo', 'creencia', 'contrapuerta', 'palacio',
						'solución', 'tocino', 'desangrar', 'hortelano', 'condiscípulo', 'descriptivo', 'observatorio', 'caótico', 'cómico', 'solevantar',
						'teólogo', 'druida', 'plata', 'videojuego', 'barómetro', 'actor', 'zapatear', 'espalda', 'pregón', 'frase',
						'intratable', 'zoológico', 'ladrillo', 'cebra', 'suerte', 'cabritilla', 'devalar', 'cuadriga', 'sadismo', 'revólver',
						'disparar', 'excursionista', 'embutido', 'encantador', 'pistón', 'homeópata', 'capilla', 'violín', 'mascarilla', 'frutal',
						'impago', 'deficiencia', 'isla', 'equiparable', 'hostil', 'conserje', 'divino', 'ética', 'veredicto', 'catálogo',
						'gentil', 'leche', 'erróneo', 'confín', 'reloj', 'tecnológico', 'chupar', 'socavón', 'jerga', 'superficie',
						'olvido', 'atar', 'radio', 'helado', 'versículo', 'elixir', 'trocear', 'lagarto', 'peligrosamente', 'mortadela',
						'croqueta', 'notaría', 'satánico', 'cuño', 'farol', 'necrosis', 'mensajero', 'saturno', 'compasivo', 'pescadería'];

datos['data_general3']=['declarar', 'delta', 'descortés', 'denominar', 'jamás', 'certeza', 'cordón', 'afeitar', 'desatado', 'filantrópico',
						'hidratar', 'socoro', 'piojo', 'programa', 'islamismo', 'entrenador', 'honda', 'servidumbre', 'desmontable', 'concha',
						'diana', 'aceitera', 'migaja', 'detestar', 'teatro', 'variz', 'simio', 'plural', 'esponja', 'descenso',
						'conducta', 'relajación', 'delirio', 'embajada', 'bibliografía', 'doblaje', 'famoso', 'embriagador', 'corazón', 'sellado',
						'gozo', 'profilaxis', 'absoluto', 'cañizal', 'mayonesa', 'codorniz', 'diabético', 'jamón', 'térmico', 'delator',
						'terapia', 'fuente', 'defecar', 'abanico', 'diáfano', 'espuma', 'cuarteto', 'escritor', 'precavido', 'roscón',
						'esclava', 'despojo', 'regional', 'ordenador', 'cooperante', 'hazaña', 'razonable', 'simposio', 'quirófano', 'detective',
						'español', 'lactosa', 'inorgánico', 'sujetador', 'curva', 'desviación', 'ególatra', 'autógrafo', 'corregir', 'fósforo',
						'simple', 'chaleco', 'redacción', 'hongo', 'musaraña', 'rebatir', 'regadera', 'circonio', 'fecal', 'promesa',
						'silla', 'imbécil', 'irónico', 'dormida', 'caudillo', 'desfile', 'cañón', 'globo', 'defoliar', 'estilográfico',
						'viajar', 'consolar', 'rocío', 'guinda', 'simbología', 'consanguíneo', 'perdigón', 'galleta', 'maceta', 'dragón',
						'capacidad', 'cuchara', 'gallo', 'chepa', 'esferoide', 'rebuznar', 'indulto', 'biodiversidad', 'enciclopedia', 'fax',
						'abandono', 'champán', 'cohecho', 'confiscar', 'filosófico', 'celta', 'importante', 'control', 'cruzada', 'recogido',
						'cianuro', 'guisado', 'loción', 'matar', 'orgía', 'apio', 'zanahoria', 'cata', 'policia', 'recreo',
						'catalepsia', 'estirón', 'celofán', 'griego', 'sobornar', 'facturar', 'sotana', 'cuartilla', 'señalizar', 'violón',
						'radar', 'férreo', 'nubosidad', 'descontento', 'monigote', 'alimaña', 'pronunciable', 'cojo', 'meñique', 'ensordecedor',
						'gel', 'rasgar', 'cretino', 'legumbre', 'cúmulo', 'manifestar', 'doncella', 'acrílico', 'numeroso', 'misil',
						'mediana', 'cuco', 'desempleo', 'digital', 'motor', 'teléfono', 'cinc', 'estafar', 'acuífero', 'muestra',
						'calabaza', 'descuidado', 'sabañón', 'llanura', 'tocadiscos', 'rancho', 'criminólogo', 'cura', 'quiromancia', 'mantequilla',
						'madera', 'rectificar', 'festejar', 'criticar', 'yoga', 'alma', 'trivial', 'demorar', 'erizo', 'experto',
						'segmento', 'sartén', 'caballería', 'fugitivo', 'congelar', 'metal', 'soluble', 'asteroide', 'hospedar', 'sentimentalismo',
						'tránsfuga', 'periscopio', 'igualar', 'fragrancia', 'pagoda', 'romanticismo', 'cuarto', 'culpabilidad', 'viñeta', 'béisbol',
						'brillo', 'dinamita', 'luciérnaga', 'niñera', 'dialecto', 'urbanita', 'escobilla', 'porcino', 'prostitución', 'manuscrito',
						'ordeñar', 'moraleja', 'troglodita', 'evangelio', 'abuela', 'cera', 'estropear', 'voleibol', 'liberal', 'dedal',
						'activar', 'patético', 'reinsertar', 'abofetear', 'coche', 'inspirador', 'despistado', 'conjunto', 'palabra', 'habilidoso',
						'cautelar', 'compota', 'evocador', 'señal', 'sentimental', 'importador', 'dentición', 'entresacar', 'adulterio', 'derivar',
						'comenzar', 'croquis', 'opcional', 'hamaca', 'localizar', 'magnolia', 'oxigenar', 'pirata', 'desértico', 'decálogo',
						'pétalo', 'estabilidad', 'sonata', 'muestra', 'cosmos', 'electrizar', 'móvil', 'común', 'espejismo', 'bolígrafo',
						'cortar', 'ferial', 'gelatina', 'derrota', 'ciempiés', 'cinta', 'conferencia', 'droga', 'entremés', 'poblar',
						'zorro', 'pomelo', 'harmonioso', 'culto', 'vahído', 'pilotaje', 'zorzal', 'copa', 'cesta', 'barco'];

datos['data_general4']=['ingestión', 'siervo', 'simulacro', 'hexágono', 'cúpula', 'fonógrafo', 'cerdo', 'hogar', 'masticar', 'tecla',
						'favorito', 'funda', 'indivisible', 'robledal', 'compás', 'censura', 'cetárea', 'celulosa', 'bisagra', 'nochevieja',
						'sumarial', 'estéril', 'explosivo', 'cohibir', 'perdedor', 'amarracos', 'moño', 'pocillo', 'copiar', 'desnutrido',
						'acuerdo', 'espiar', 'juguete', 'debatir', 'flequillo', 'corto', 'gotera', 'copropietario', 'obispado', 'estudio',
						'desastre', 'iconográfico', 'desequilibrado', 'pastilla', 'intelectual', 'clavija', 'eclipse', 'fabricante', 'eréctil', 'nasal',
						'muela', 'descaro', 'aceptar', 'volcán', 'capital', 'desnivel', 'desempolvorar', 'utopía', 'ejercer', 'congreso',
						'milhojas', 'estuche', 'contar', 'constructor', 'puro', 'comodidad', 'rodaje', 'alarma', 'escolar', 'forúnculo',
						'comprar', 'conserva', 'constatar', 'oleoso', 'salvar', 'dúplex', 'fecha', 'líder', 'coloración', 'cepa',
						'hueso', 'abeja', 'cosquillas', 'cuaderno', 'esperma', 'incoherencia', 'coprófago', 'pentágono', 'remojar', 'cerveza',
						'descomunal', 'gamuza', 'conducir', 'laberinto', 'chica', 'cocinero', 'coliflor', 'inglés', 'loncha', 'previo',
						'aristocracia', 'dilatador', 'devolución', 'aduana', 'cautivo', 'pota', 'viernes', 'compadre', 'xilófono', 'confianza',
						'lóbulo', 'crisis', 'picar', 'encubridor', 'charca', 'cubo', 'infección', 'yogurtera', 'decimal', 'multicolor',
						'sincerar', 'vejiga', 'neón', 'corona', 'embarazada', 'desnudo', 'océano', 'doctoral', 'marisco', 'acecho',
						'exprimir', 'hormigón', 'larva', 'fórmula', 'pancarta', 'ideal', 'mafia', 'signo', 'dandi', 'gratis',
						'transeúnte', 'coyote', 'manzana', 'fósil', 'impulso', 'inamovible', 'sosiego', 'correo', 'desdén', 'cadáver',
						'budismo', 'andanza', 'abubilla', 'cérvido', 'desapego', 'sintonía', 'costura', 'ensayar', 'casa', 'fluido',
						'catedral', 'abogacía', 'avión', 'encabezado', 'jubiloso'];

datos['data_infantil']=['Pocoyó', 'Dora', 'muñeca', 'Nancy', 'negro', 'martes', 'gato', 'madrina', 'enero', 'rosa',
						'libro', 'junio', 'princesa', 'mano', 'verde', 'vaca', 'mayo', 'oreja', 'cama', 'galletas',
						'casa', 'patatas', 'autobús', 'mochila', 'enanito', 'lobo', 'patio', 'sonajero', 'bruja', 'Pajaroto',
						'pota', 'cocodrilo', 'tierra', 'vacaciones', 'palabra', 'arena', 'calle', 'Mickey', 'coche', 'manzana',
						'madrastra', 'abuela', 'guantes', 'diciembre', 'minuto', 'encerado', 'grande', 'malo',
						'patinete', 'jueves', 'delgado', 'profesora', 'rotulador', 'Caillou', 'jamón', 'pelota', 'merienda',
						'abril', 'tenedor', 'cacahuete', 'oscuro', 'cenicienta', 'Kitty', 'jerséi', 'domingo',
						'cuento', 'papa', 'carnaval', 'rojo', 'trenza', 'navidad', 'ceja', 'tiburón', 'colegio', 'ballena',
						'primavera', 'libreta', 'azul', 'bolígrafo', 'Elly', 'educado', 'año', 'feo', 'madera', 'hielo',
						'amarillo', 'blancanieves', 'televisión', 'patines', 'camisa', 'patinaje', 'contento',
						'mes', 'ordenador', 'Gargamel', 'noviembre', 'cabeza', 'tío', 'tomate', 'escribir',
						'plato', 'padrino', 'tebeo', 'inglés', 'dedo', 'miércoles', 'bueno', 'semáforo', 'cocina',
						'abuelo', 'lápiz', 'gris', 'huevos', 'recreo', 'chándal', 'Perezoso', 'sábado', 'cena',
						'letra', 'melón', 'agosto', 'gimnasia', 'coleta', 'cerdo', 'segundo', 'sal',
						'Sabio', 'tía', 'cuchillo', 'biberón', 'febrero', 'Pitufos', 'bufanda', 'pez', 'habitación',
						'conejo', 'tarta', 'Piolín', 'pie', 'sandía', 'castillo', 'Mudito', 'chupete', 'lechuga',
						'camión', 'navidades', 'sol', 'bicicleta', 'hombro', 'profesor', 'comida', 'triste',
						'caramelo', 'cajón', 'pan', 'zapatos', 'Dormilón', 'luna', 'julio', 'puerta', 'pijama',
						'león', 'guardería', 'lunes', 'cuchara', 'calcetines', 'mama','caballo',
						'alto', 'gafas', 'piruleta', 'deberes', 'octubre', 'leer', 'gallina', 'aire', 'nubes', 'día',
						'Gruñón', 'viernes', 'pelo', 'pantalón', 'Pitufina', 'estrella', 'cera', 'serpiente',
						'obediente', 'vaso', 'ciudad', 'verano', 'cubo', 'rodilla', 'mar', 'tijeras', 'azúcar',
						'mayor', 'matemáticas', 'brazo', 'ombligo', 'marzo', 'ascensor', 'desayuno',
						'pera', 'gorro', 'cepillo', 'amigos', 'armario', 'goma', 'agua',  'camiseta', 'sábana',
						'ratón', 'Tímido', 'lazo', 'otoño', 'ojo', 'palomitas',
						'invierno', 'sartén',  'techo', 'cine', 'pala', 'uvas', 'pequeño', 'elefante',
						'gordo', 'manta', 'chocolate', 'ventana', 'bonito', 'reir', 'zapatillas',
						'claro', 'película', 'bajo', 'mando', 'jabón', 'regalo', 'leche', 'Loula', 'plátano',
						'pulpo', 'Mocoso', 'silla', 'pestaña', 'taza', 'rastrillo',
						'llorar', 'septiembre', 'Pato'];

datos['data_tech']=['Macintosh', 'Google', 'byte', 'Xerox', 'bucle', 'SmartPhone', 'Chrome', 'CSS', 'PlayBook', 'Java',
						'TTL', 'Nginx', 'PHP', 'Modem', 'Applet', 'DDoS', 'puntero', 'Quicktime', 'XML', 'CD-ROM',
						'Zettabyte', 'Terra', 'DVD', 'Twitter', 'UNIX', 'Hoax', 'SSH', 'Ubuntu', 'TeraByte', 'Firewall',
						'hosting', 'Fon', 'Excite', 'servidor', 'impresora', 'jumper', 'SUN', 'Kerberos', 'FTP', 'ICANN',
						'KVM', 'Moore', 'Lynx', 'MCU', 'TCP', 'Yahoo', 'procesador', 'ISO', 'Amazon', 'iPad',
						'multidifusión', 'Netscape', 'RAM', 'LAN', 'FAT', 'Gmail', 'Google+', 'majordomo', 'PKI', 'webcam',
						'Apple', 'ODBC', 'PDA', 'Safari', 'TIFF', 'OSI', 'Ogg', 'Microsoft', 'eBay', 'Podcast',
						'Spam', 'tar', 'MTA', 'UPS', 'VGA', 'vínculo', 'GIMP', 'VoIP', 'P2P', 'RJ45',
						'Wiki', 'XUL', 'Youtube', 'BlackBerry', '486', 'NTFS', 'W3C', 'Opera', 'warez', 'Intel',
						'WAP', 'UML', 'unicast', 'OpenBSD', 'Perl', 'memoria', 'TIC', 'Photoshop', 'Worm', 'Xeon',
						'Lazaridis', 'Messenger', 'Adsense', 'RIM', 'Bug', 'Excel', 'Hotmail', 'Cobol', 'GET', 'Sysop',
						'HTML', 'POST', 'Cookie', 'Debug', 'unicode', 'desfragmentar', 'Python', 'Cherokee', 'JSP', 'macro',
						'Adwords', 'Tomcat', 'C++', 'compilador', 'QuickBasic', 'Coldfusion', 'FORTRAN', 'CPU', 'LISP', 'OOP',
						'EDGE', 'ROM', 'Firefox', 'PROLOG', 'constante', 'Microprocesador', 'Avatar', 'IRC', 'variable', 'VCR',
						'WEP', 'ActiveX', 'PDF', 'Balsillie', 'VESA', 'ASCII', 'weblog', 'hipervínculo', 'GDI', 'shell',
						'SDK', 'Geek', 'NETBIOS', 'tag', 'Token', 'thread', 'RSA', 'VHS', 'tóner', 'IDE',
						'Hotspots', 'GPS', 'Hub', 'GSM', 'ATM', 'URL', 'Squid', 'JPG', 'MHz', 'Pop-Up',
						'Foursquare', 'talk', 'Plasma', 'ASP', 'SATA', 'WYSIWYG', 'FreeBSD', 'Mint', 'Nuke', 'USB',
						'puerto', 'Wikipedia', 'Sniffer', 'overclocking', 'paquete', 'binario', '8086', 'RAID', 'proxy', 'RGB',
						'Mosaic', 'PC', 'NAT', 'Facebook', 'PGP', 'eMule', 'Winchester', 'Sendmail', 'HDMI', 'usuario',
						'OpenOffice', 'Oracle', 'Gusano', 'latencia', 'BBS', 'malware', 'API', 'Blog', 'JavaScript', 'Freeware',
						'Debian', 'Pentium', 'Chroma', 'PayPal', 'Ethernet', 'QWERTY', 'Copyleft', 'IBM', 'e-book', 'MIPS',
						'WiMAX', 'Phishing', 'Emoticon', 'Apache', 'iTunes', 'MS-DOS', 'CGI', 'Word', 'DHCP', 'Windows',
						'Ansi', 'CSV', 'Servlet', 'LDAP', 'Skype', 'Kindle', 'troyano', 'Telnet', 'IIS', 'Adobe',
						'Torrent', 'ActionScript', 'PING', 'Banner', 'RAMDAC', 'navegador', 'GIF', 'netiqueta', 'Nook', 'IP',
						'XSLT', 'RSS', 'teclado', 'Eclipse', 'BSD', 'SAN', 'MP3', 'hacker', 'sudo', 'Webworks',
						'HDTV', 'RTP', 'MPEG', 'SSL', 'PCMCIA', 'toner', 'Android', 'MAPI', 'AOL', 'wav',
						'SCSI', 'POP', 'IMAP', 'códec', 'VRML', 'PNG', 'LibreOffice', 'software', 'GPL', 'Wii',
						'MySQL', 'SEO', 'YUV', 'contraseña', 'SOAP', 'H.264', 'virus', 'Ruby', 'OCR', 'Rsync',
						'SQL', 'NFS', 'Chat', 'Firewire', 'intranet', 'lossless', 'teletexto', 'web', 'PCI', 'WAN'];
